### ISSUE TITLE
Invalid name for attribute publishedby

### ISSUE THREAD

**Issue by johnmsaxton** [microsoft/mwx-teams-vaccine-attestation#1]
Receiving this error 5 times when I attempt to import the solution: 

Invalid name for attribute publishedby. Custom attribute names must start with a valid customization prefix. The prefix for a solution component should match the prefix that is specified for the publisher of the solution.

**Comment by junterpfe** [comment]
Can you attempt to make a test table in the Teams Dataverse?
Open PowerApps in teams, See more in recent apps, this should show a list of teams on the left, choose the one you are trying to import into, click see all in the list "built by this team" in the new screen you should see tables on the left, click that, then New > Table give it some name like "test" (we will delete it later) then once that is made try the import again
make sure to follow step 8
https://github.com/microsoft/mwx-teams-vaccine-attestation/wiki/Deployment-guide#3-import-the-solution-to-teams-dataverse
and only import the tables listed in the guide.

let us know if that works.

if it does you can delete the test table.

**Comment by sbjcs2232632tex** [comment]
For myself, I had to give it a little bit of time after the Environment was ready, and then go to import the solution again before the ability to select solution component tables to import were ready. Agree with above that it sounds like you may have selected more than the tables indicated in the Deployment Guide.

**Comment by junterpfe** [comment]
@johnmsaxton any luck?

**Comment by johnmsaxton** [comment]
> For myself, I had to give it a little bit of time after the Environment was ready, and then go to import the solution again before the ability to select solution component tables to import were ready. Agree with above that it sounds like you may have selected more than the tables indicated in the Deployment Guide.

This seems like what happened to me.  I was tied up with other work. When I came back, like magic  VaxApp was in my Team. I am the only person who has access to this environment so it must have been some kind of delayed  response even though the install appeared to fail.  Its a little weird that this happened. I am going to remove it and try adding it again. 

![image](https://user-images.githubusercontent.com/20325713/135180454-aa4e5550-2e71-46a4-90d7-e0a6d563326b.png)

**Comment by junterpfe** [comment]
We may need to add in a "let it bake" time after the creation of the Dataverse, seems like some people are running into this if there is any kind of delay in the database build on the backend.

Let us know if it works when you re-deploy and if it is ok to close this @johnmsaxton.

**Comment by junterpfe** [comment]
looks like it just takes time to provision and we will add notes related to that.

**Comment by HartnettMJ** [comment]
So I'm getting the same error as shown in @johnmsaxton's screenshot above.  "Office365Gropus.ListGroup Members failed: The method 'ListGroupMembers' has an invalid value for parameter 'groupId'.   Was this ever addressed?

**Comment by junterpfe** [comment]
it looks like this was in the actual app, are your settings like this?
![image](https://user-images.githubusercontent.com/47872678/138739503-66893134-c144-411a-89fd-759324c3ebc4.png)
with your "admin" group in place of the GUID on the screenshot?

**Comment by junterpfe** [comment]
Value in the Name column should be "Settings", value in the AdminGroupGuid should be the Azure AD group that you are using for the Admins of the application.

**Comment by HartnettMJ** [comment]
> Value in the Name column should be "Settings", value in the AdminGroupGuid should be the Azure AD group that you are using for the Admins of the application.

OK, yeah that was my issue.  I hadn't done that step yet.  I'm good there now.
