### ISSUE TITLE
Update to Section 04 Screenshot (case-sensitive Name field)

### ISSUE THREAD

**Issue by sbjcs2232632tex** [microsoft/mwx-teams-vaccine-attestation#2]
![Screenshot 2021-09-26 161716](https://user-images.githubusercontent.com/61771497/134822785-d482e4c7-8f1d-491f-8809-e979e21cf6ea.png)

Recommend updating screenshot in [section 4](https://github.com/microsoft/mwx-teams-vaccine-attestation/wiki/deployment-guide#updating-app-admin-group), as it stands, folks implementing will run into an issue since it appears to be case sensitive. So, updating from "settings" to "Settings" in screenshot

Thanks for all the hard work you all put into this!

**Comment by junterpfe** [comment]
Screenshot updated, thanks for the catch!
