### ISSUE TITLE
Configure Application Text Not Working

### ISSUE THREAD

**Issue by SolutionScope** [microsoft/mwx-teams-vaccine-attestation#3]
I have installed this app as per the deployment guide. When I input text into the fields in the Configure Solution Settings screen (i.e. Configure Application Text), none of the text that I input appears on the attestation form. See the screenshots below. 

I was able to successfully update the other configuration items including: Work Locations, Attestation Statuses, and Useful Linls.

Teams Version:
You have Microsoft Teams Version 1.4.00.26376 (64-bit). It was last updated on 2021-09-25.

![image](https://user-images.githubusercontent.com/84244780/135950451-233c26aa-d3cc-469b-93a8-978c9d2647cf.png)

![image](https://user-images.githubusercontent.com/84244780/135950508-c2c1455d-3b00-4603-8679-a2e47f3a4bfc.png)

**Comment by junterpfe** [comment]
https://github.com/microsoft/mwx-teams-vaccine-attestation/wiki/Deployment-guide#4-configuration-of-app-settings

when checking here do you see the data in the table?
Also make sure the "Name" column on the row is "Settings" it is case sensitive.

also there should only be one row of data.

let us know if it works out editing as above and we will re-check the app.

**Comment by SolutionScope** [comment]
Changing the Name column to Settings solved this issue. As per the deployment guide, I originally had "AdminGroupGuid" in the Name column for the 1 row. Thanks for your help!
