### ISSUE TITLE
Error importing app package into PowerApps

### ISSUE THREAD

**Issue by zsrobertson84** [microsoft/mwx-teams-vaccine-attestation#5]
I am receiving the following error when trying to import the zip package. If I cannot get passed this it is a show stopper for us.

Customizations from file "Vaccine App - v1.10.zip" failed to import: Invalid name for attribute publishedby. Custom attribute names must start with a valid customization prefix. The prefix for a solution component should match the prefix that is specified for the publisher of the solution.

**Comment by desmay** [comment]
@zsrobertson84  Did you just create a new Teams dataverse and trying to import the app? We seen issues where the background tasks where still provisioning db and retrying the import after sometime resolved the issue.

**Comment by zsrobertson84** [comment]
I created a new private team and went through the process of adding the "Vaccination Attestation" PowerApp as a tab. Everything was seemleess until the portion where I needed to upload the app package. I could not find where to import the package. All this was done last week and then today was able to find where to import the zip file that I downloaded. I have tried uploading it 3 different times over the last few hours and same result. I even spoke with Microsoft PowerApps team and they said they couldn't give any real advice because it was not an officially supported app by Microsoft.

**Comment by desmay** [comment]
@zsrobertson84  After selecting the zip file on import did you unselect tables not required by app. This is step 7 under the import solution section?

**Comment by zsrobertson84** [comment]
Yes I did unselect the tables not required. However, I have one that shows up for me that is not listed in the documentation as atll. I have attached a screenshot so you can see what I am referring to
![Vax App Import](https://user-images.githubusercontent.com/92391201/137002257-cdff3349-32a0-492b-9662-6877115ba014.gif)
.

**Comment by desmay** [comment]
Yes please import the AttestationVacHold table.  Can you post screenshot of the error message?

**Comment by zsrobertson84** [comment]
You bet I can. Here it is
![Error uploading app package](https://user-images.githubusercontent.com/92391201/137006151-f72e4e48-cd97-4a79-98da-047e6e42791b.gif)
.

**Comment by desmay** [comment]
Can you provision a test table within same environment ? Try clicking on Tables > New Table.

**Comment by zsrobertson84** [comment]
No issues create a test table eithe
![Test Table](https://user-images.githubusercontent.com/92391201/137012545-8edf4a23-5724-4e97-a813-ee2be2cb402d.gif)
r.

**Comment by junterpfe** [comment]
Now that you were able to make the table, delete the test tables and the app (it looked like it did import at some point? at least the app i see in another screenshot) then try a re-import?

**Comment by zsrobertson84** [comment]
so by deleting the tables and app, I was then able to import successfully but having trouble figuring out where to navigate for the next step
![Next Steps](https://user-images.githubusercontent.com/92391201/137055833-0f3ce271-9f54-4fc4-83d3-5cffb08228e4.gif)
![Solutions](https://user-images.githubusercontent.com/92391201/137055927-2877f4d1-41f8-4979-80f5-ad8e3195f53a.gif)
s.

**Comment by desmay** [comment]
@zsrobertson84 I updated guide, it looks like changes were made to the Teams Dataverse import process. From your screen above click on the VaxApp, it should open in PowerApps and click on the Publish to Team option.

**Comment by zsrobertson84** [comment]
I really appreciate the assistance you have provided in this. I definitely see where you have updated the documentation. I was able to to get past this blocker and a further on in this process. I do have a couple questions though. In "Configure Solution Settings" I have entered some text into the field for Privacy Statement but it does not display when on the screen to acknowledge privacy statement. Why is that or am I missing something. The other question I have is how do you view the data submissions in the CDS Database or do I have to use the option to export to a SharePoint list since its a Microsoft Database
![Settings for VaxApp](https://user-images.githubusercontent.com/92391201/137174064-9ddc9661-2b62-43e1-8f49-22bbca312b4d.gif)
![Privacy Statement](https://user-images.githubusercontent.com/92391201/137174079-c100fa13-0983-429a-9c18-0d19761c4127.gif)
e?

**Comment by desmay** [comment]
@zsrobertson84 In the solution settings table did you enter the word (case sensitive) Settings for Name ?
![image](https://user-images.githubusercontent.com/43035577/137175293-90cdc553-5a7c-446c-b837-84c722f39b8a.png)

Each user can view their own attestations but if you want to view them all you can export data from table. There is a wiki page on steps to export data https://github.com/microsoft/mwx-teams-vaccine-attestation/wiki/how-to-export-Vaccine-Attestation-Data

**Comment by zsrobertson84** [comment]
That is where I made my mistake. In the name column I actually named it AdminGroupGuid instead of Settings. It Started working right away. I think I am going to give it a shot with exporting to a SharePoint list because we have a requirement to be able to actually view the image of the vaccine cards. One last question for the time being for you. What is the purpose of the wording "Text" in a few fields of the form? Is there a way to remove that or is that a necessity of a text field to provide an error of some sort if there is on
![Purpose of word text](https://user-images.githubusercontent.com/92391201/137180756-30a05eaa-65e8-4cc2-b4db-86daa7dce612.gif)
e?

**Comment by desmay** [comment]
The "text" word is just placeholder data, once you enter all data into settings table these labels will have appropriate data values from table. 
Please let me know if there is anything else or if we can close this issue.  Thank you for reporting  issues with documentation.

**Comment by zsrobertson84** [comment]
Thank you for all your help. I have the app up and running now. If I get confused on anything from the wiki page documentation on the export into SharePoint List process I can open a new issue since it that would be separate of this anyways. This app is going to be a game changer.
