### ISSUE TITLE
Having issues importing

### ISSUE THREAD

**Issue by HartnettMJ** [microsoft/mwx-teams-vaccine-attestation#7]
When attempting to Import the zip file, I am getting an error.  The message in the error log says, "The entity relationship role of the referencing entity is required when creating a new one-to-many entity relationship lk_cr8f3_attestationvachold_createdby."

**Comment by HartnettMJ** [comment]
I figured it out after looking at closed issue #5.  You really should consider updating the deployment guide to include checking "AttestationVacHold".

**Comment by zsrobertson84** [comment]
Glad to see my thread of issue I was having helped someone else out as well.

**Comment by desmay** [comment]
> I figured it out after looking at closed issue #5. You really should consider updating the deployment guide to include checking "AttestationVacHold".

I just updated the image. Thanks for reporting the outdated image.
